// Generated by Cypress Author on 2026-06-23.

describe('Login no Sauce Demo', () => {
  beforeEach(() => {
    cy.fixture('dados').as('dadosLogin');
    cy.acessaPaginaLogin();
  });

  it('realiza login com usuario padrao -> exibe a pagina de produtos', function () {
    // O spec fica focado no cenario enquanto os detalhes de interacao ficam nos comandos.
    cy.realizaLogin(this.dadosLogin.usuarioSucesso);
    cy.validaPaginaProdutos();
  });

  it('tenta login com usuario bloqueado -> exibe mensagem de bloqueio', function () {
    cy.realizaLogin(this.dadosLogin.usuarioBloqueado);
    cy.validaErroDeLogin('locked out');
  });

  it('tenta login com senha incorreta -> exibe mensagem de credenciais invalidas', function () {
    cy.realizaLogin(this.dadosLogin.usuarioIncorreto);
    cy.validaErroDeLogin('Username and password do not match');
  });
});
